FROM node:15.14.0-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . ./
COPY config.prod.tsx /app/src/config.tsx
RUN npm run build
FROM nginx:1.15
COPY --from=builder /app/build/ /usr/share/nginx/html 
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
